apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.78.2
  values:
    rbac:
      enabled: "true"
    acme:
      enabled: "true"
      challengeType: "http-01"
      email: "team@shabados.com"
      staging: "false"
    ssl:
      enabled: "true"
      enforced: "true"
      permanentRedirect: "true"